CREATE TABLE IF NOT EXISTS user_status (
    id SERIAL PRIMARY KEY,
    type VARCHAR(16) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS "user" (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (MAXVALUE 99999999),
    email VARCHAR (255) UNIQUE NOT NULL,
    username VARCHAR (32) UNIQUE NOT NULL,
    password VARCHAR (128) NOT NULL,
    profile_picture VARCHAR (80),
    status INT DEFAULT 1 NOT NULL REFERENCES user_status (id), 
    created_at TIMESTAMP DEFAULT now() NOT NULL
);

CREATE UNIQUE INDEX idx_email ON "user" (
    email,
    password
);

CREATE UNIQUE INDEX idx_username ON "user" (
    username
);

CREATE TABLE "session" (
  "sid" VARCHAR NOT NULL COLLATE "default",
  "sess" JSON NOT NULL,
  "expire" TIMESTAMP(6) NOT NULL
)
WITH (OIDS=FALSE);

ALTER TABLE "session" 
ADD CONSTRAINT "session_pkey" PRIMARY KEY ("sid") NOT DEFERRABLE INITIALLY IMMEDIATE;

CREATE INDEX "IDX_session_expire" ON "session" ("expire");

CREATE TABLE IF NOT EXISTS relationship_type (
    id SERIAL PRIMARY KEY,
    type VARCHAR(16) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS relationship (
    id SERIAL PRIMARY KEY,
    type INT UNIQUE NOT NULL,
    actor INT NOT NULL,
    target INT NOT NULL,
    UNIQUE (actor, target),
    FOREIGN KEY (type)
        REFERENCES relationship_type (id),
    FOREIGN KEY (actor)
        REFERENCES "user" (id),
    FOREIGN KEY (target)
        REFERENCES "user" (id)
);

CREATE TABLE IF NOT EXISTS conversation_type (
    id SERIAL PRIMARY KEY,
    type VARCHAR(32) DEFAULT 1 NOT NULL
);

CREATE TABLE IF NOT EXISTS conversation (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (MINVALUE 100000000),
    owner INT CONSTRAINT is_dm CHECK (type = 1 OR owner IS NOT NULL),
    type INT DEFAULT 1 NOT NULL,
    name VARCHAR(32),
    avatar VARCHAR(80),
    FOREIGN KEY (owner)
        REFERENCES "user" (id),
    FOREIGN KEY (type)
        REFERENCES conversation_type (id)
);

CREATE TABLE IF NOT EXISTS conversation_participant (
    id  SERIAL PRIMARY KEY,
    conversation INT NOT NULL,
    "user" INT NOT NULL,
    joined_at TIMESTAMP DEFAULT now() NOT NULL,
    left_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT now() NOT NULL,
    FOREIGN KEY (conversation)
        REFERENCES conversation (id),
    FOREIGN KEY ("user")
        REFERENCES "user" (id)
);

CREATE INDEX idx_cp_convo ON "conversation_participant" (
    conversation
);

CREATE INDEX idx_cp_user ON "conversation_participant" (
    "user"
);

CREATE TABLE IF NOT EXISTS message_type (
    id SERIAL PRIMARY KEY,
    type VARCHAR(32) NOT NULL
);

CREATE TABLE IF NOT EXISTS message (
    id SERIAL PRIMARY KEY,
    author INT NOT NULL,
    conversation INT NOT NULL,
    type INT DEFAULT 1 NOT NULL,
    data TEXT,
    media_url VARCHAR(255),
    description TEXT,
    parent INT,
    created_at TIMESTAMP DEFAULT now() NOT NULL,
    modified_at TIMESTAMP,
    FOREIGN KEY (author)
        REFERENCES "user" (id),
    FOREIGN KEY (conversation)
        REFERENCES conversation (id),
    FOREIGN KEY (type)
        REFERENCES message_type (id),
    FOREIGN KEY (parent)
        REFERENCES message (id)
);

CREATE UNIQUE INDEX idx_msg_convo ON "message" (
    id,
    conversation
);

-- CREATE TABLE IF NOT EXISTS attachment (
--     id SERIAL PRIMARY KEY,
--     message INT NOT NULL,
--     file_name VARCHAR(255) NOT NULL,
--     url VARCHAR(255) NOT NULL,
--     FOREIGN KEY (message)
--         REFERENCES message (id)
-- );

-- CREATE UNIQUE INDEX idx_att_msg ON "attachment" (
--     message
-- );


-- CREATE TABLE IF NOT EXISTS unread_messages (
--     id SERIAL PRIMARY KEY,
--     message INT NOT NULL,
--     "user" INT NOT NULL,
--     FOREIGN KEY (message)
--         REFERENCES message (id),
--     FOREIGN KEY ("user")
--         REFERENCES "user" (id)
-- );


INSERT INTO user_status (
    type
) VALUES ('offline');

INSERT INTO user_status (
    type
) VALUES ('online');

INSERT INTO user_status (
    type
) VALUES ('away');


INSERT INTO user_status (
    type
) VALUES ('dnd');


INSERT INTO relationship_type (
    type
) VALUES ('friend');

INSERT INTO relationship_type (
    type
) VALUES ('blocked');

INSERT INTO relationship_type (
    type
) VALUES ('sent request');

INSERT INTO relationship_type (
    type
) VALUES ('received request');

INSERT INTO conversation_type (
    type
) VALUES ('dm');

INSERT INTO conversation_type (
    type
) VALUES ('group chat');

INSERT INTO message_type (
    type
) VALUES ('text');

INSERT INTO message_type (
    type
) VALUES ('gif');

INSERT INTO message_type (
    type
) VALUES ('image');

CREATE  FUNCTION update_modified_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.modified_at = now();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_modified_table
    BEFORE UPDATE
    ON
        message
    FOR EACH ROW
EXECUTE PROCEDURE update_modified_at();
